name: C CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: docker build --progress=plain --target test -t ecs-test .

      - name: Coverage
        run: docker build --progress=plain -t ecs-coverage .